spring:
  profiles:
    active:
      - dev

---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-phil-dev

---
spring:
  profiles: test
  application:
    name: microservicecloud-config-phil-test
# 必须保存文件为utf-8
